services:
  mnestix-aas-generator:
    image: mnestix-aas-generator
    build: ./../.
    container_name: mnestix-aas-generator
    # Port Mapping
    # Map host port 5064 to container port 5064
    ports:
      - "5064:5064"
    environment:
      # Application Settings
      # API Key:
      CustomerEndpointsSecurity__ApiKey: YOUR_API_KEY_HERE
      # Connection to Services:
      ReverseProxy__Clusters__aasRepoCluster__Destinations__destination1__Address: "http://aas:8081/"
      ReverseProxy__Clusters__submodelRepoCluster__Destinations__destination1__Address: "http://aas:8081/"
      ReverseProxy__Clusters__discoveryCluster__Destinations__destination1__Address: "http://aas-discovery:8081/"
      # Features Configuration
      Features__AasRegistryMiddleware: true
      Features__AllowRetrievingAllShellsAndSubmodels: true
      Features__UseAuthentication: true
      # InfluxDB Configuration
      # URL to specify the host and port where InfluxDB is running:
      ReverseProxy__Clusters__influxCluster__Destinations__destination1__Address: "http://example/"
      # Token:
      ReverseProxy__Routes__InfluxRoute__Transforms__1__Set: "Token "
      # MongoDB Configuration
      BasyxDbConnectionConfiguration__MongoConnectionString: "mongodb://mongoAdmin:mongoPassword@mongodb:27017/?authSource=admin"
      BasyxDbConnectionConfiguration__DatabaseName: basyxdb
      BasyxDbConnectionConfiguration__AasCollectionName: "aas-repo"
      # OpenId repository settings
      RepositoryOpenIdConnect__EnableRepositoryOpenIdAuth: "false"
      RepositoryOpenIdConnect__Authority: "http://keycloak:8080/realms/BaSyx"
      RepositoryOpenIdConnect__DiscoveryEndpoint: ".well-known/openid-configuration"
      RepositoryOpenIdConnect__ClientId: "mnestix-repo-client-demo"
      RepositoryOpenIdConnect__ClientSecret: "your-client-secret"
      RepositoryOpenIdConnect__ValidateIssuer: "false"
      RepositoryOpenIdConnect__TokenEndpoint: "http://keycloak:8080/realms/BaSyx/protocol/openid-connect/token"
      # Microsoft Authentication and Authorization Configuration:
      AzureAd__Domain: "your-domain.onmicrosoft.com"
      AzureAd__TenantId: your-tenant-id
      AzureAd__ClientId: your-client-id
      # OpenID Configuration
      OpenId__EnableOpenIdAuth: "false"
      OpenId__Issuer: "http://keycloak:8080/realms/BaSyx"
      OpenId__ClientID: "mnestixApi-demo"
      OpenId__RequireHttpsMetadata: "false"
      # ASP.NET Core URLs
      ASPNETCORE_URLS: "http://+:5064"
    depends_on:
      aas:
        condition: service_healthy # only after the healthcheck in aas is successful, the mnestix container is being created
      keycloak:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    # Provide mongo config
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    healthcheck:
      test: echo "db.runCommand("ping").ok" | mongosh mongodb:27017/test --quiet
      interval: 3s
      timeout: 3s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  aas:
    image: eclipsebasyx/aas-environment:2.0.0-milestone-03.1
    container_name: aas
    ports:
      - "8081:8081"
    environment:
      # MongoDb configuration for Basyx Repository
      BASYX__BACKEND: MongoDB
      SPRING__DATA__MONGODB__HOST: mongodb
      SPRING__DATA__MONGODB__DATABASE: basyxdb
      SPRING__DATA__MONGODB__authentication-database: admin
      SPRING__DATA__MONGODB__USERNAME: mongoAdmin
      SPRING__DATA__MONGODB__PASSWORD: mongoPassword
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 100000KB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 100000KB
      # Allow mnestix frontend and backend to call basyx
      BASYX_CORS_ALLOWED-ORIGINS: http://localhost:3000,http://localhost:5064
      BASYX_CORS_ALLOWED-METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      # Authorization
      basyx.feature.authorization.enabled: "false"
      basyx.feature.authorization.type: rbac
      basyx.feature.authorization.jwtBearerTokenProvider: keycloak
      basyx.feature.authorization.rbac.file: file:/data/rbac_rules.json
      spring.security.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:8080/realms/BaSyx
    volumes:
      - ./data/keycloak/rbac_rules.json:/data/rbac_rules.json:ro
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck: # check the endpoint for a valid response (service ready)
      test: curl -f http://localhost:8081/actuator/health
      interval: 30s
      timeout: 10s
      retries: 6
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
  
  
  aas-discovery:
    image: eclipsebasyx/aas-discovery:2.0.0-milestone-03.1
    container_name: aas-discovery
    ports:
      - "8082:8081"
    environment:
      BASYX__BACKEND: MongoDB
      SPRING__DATA__MONGODB__HOST: mongodb
      SPRING__DATA__MONGODB__DATABASE: basyxdb
      SPRING__DATA__MONGODB__authentication-database: admin
      SPRING__DATA__MONGODB__USERNAME: mongoAdmin
      SPRING__DATA__MONGODB__PASSWORD: mongoPassword
      BASYX__CORS__ALLOWED-ORIGINS: '*'
      BASYX__CORS__ALLOWED-METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck: # check the endpoint for a valid response (service ready)
      test: curl -f http://localhost:8081/actuator
      interval: 30s
      timeout: 10s
      retries: 6
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  keycloak:
    build:
      context: ./data/keycloak
    container_name: keycloak
    volumes:
      - ./data/keycloak/realm:/opt/jboss/keycloak/imports
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_SPI_INITIALIZER_ISSUER_BASE_URI: http://keycloak:8080
      KC_HEALTH_ENABLED: true
    command: [ "start-dev", "--import-realm" ]
    healthcheck: # check the endpoint for a valid response (service ready)
      test: [ 
        "CMD-SHELL",
        'exec 3<>/dev/tcp/localhost/8080; echo -e "GET /health/ready HTTP/1.1\nhost: localhost:8080\n" >&3; timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; ERROR=$?; exec 3<&-; exec 3>&-; exit $ERROR'
      ]
      interval: 30s
      timeout: 10s
      retries: 6